[package]
name = "time_freq_gui"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eframe = "*"
env_logger = "*"
egui_plot = "*"
realfft = "*"
rustfft = "*"
